webFrameWorkProject/config/routes.rb
WebFrameWorkProject::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  root 'recipes#search'

  get 'sign_up' => 'users#new'
  post 'registered' => 'users#create'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"

  get 'user' => 'users#show'
  
  get 'newrecipe' => 'recipes#new'
  get 'created' => 'recipes#create'
  post 'created' => 'recipes#create'

  get 'search' => 'recipes#search'
  post 'results' => 'recipes#results'

  get 'show' => 'recipes#show', :as => 'show'

  get 'favourite' => 'recipes#favourite', :as => 'favourite'
  get 'unfavourite' => 'recipes#unfavourite', :as => 'unfavourite'
  get 'favourites' => 'recipes#favourites', :as => 'favourites'

  get 'delete' => 'recipes#delete', :as => 'delete'

  get 'follow' => 'users#follow', :as => 'follow'
  get 'unfollow' => 'users#unfollow', :as => 'unfollow'
  get 'following' => 'users#following', :as => 'following'

  get 'category' => 'recipes#category', :as => 'category'
  get 'category_result' => 'recipes#category_result', :as => 'category_result'

end

webFrameWorkProject/app/models/recipe.rb
class Recipe < ActiveRecord::Base
	belongs_to 	:feed
	belongs_to	:category
	has_many 	:favourites

	has_attached_file :avatar, :styles => { :small => "200x200>", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/Koala.jpg"
  	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  	do_not_validate_attachment_file_type :avatar

end

webFrameWorkProject/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  def new
	 @recipe = Recipe.new
  end
 
  def create
    recipe_params = params.require(:recipe).permit(:title, :ingredients, :instructions, :category_id, :avatar)

    @recipe = Recipe.new(recipe_params)
    @recipe.feed = @current_user.feed
  	if @recipe.save!
      @followings = Following.where("feed_id =?", @recipe.feed.id)
      if @followings.present?
        @to_users = ''
        @followings.each do |a|
          @to_users << a.user.email
          @to_users << ','
        end
        @from_user = @recipe.feed.user.firstname
        @title = @recipe.title
        @ingredients = @recipe.ingredients
        @instructions = @recipe.instructions
        FollowingMailer.new_recipe_email(@to_users, @from_user, @title, @ingredients, @instructions).deliver
      end
      redirect_to user_path(:id => @current_user.id)
    else
      flash[:notice] = "Recipe not saved"
      render 'new'
    end
  end

  def delete
    delete_params = params.require(:recipe).permit(:recipe_id)
    @delete = Recipe.where("id = ?", delete_params[:recipe_id]).take 
    @delete.destroy

    @delete_favourite = Favourite.where("recipe_id = ?", delete_params[:recipe_id])
    @delete_favourite.each do |t|
      t.destroy
    end

    redirect_to user_path(:id => @current_user.id)
  end

  def search
    @page_header = "Latest recipes"
    @recipes = Recipe.all.reverse
    @users = nil
  end
  
  def results
     search_params = params[:search]
     @page_header = "Search results for: #{search_params}" 
     @recipes = Recipe.find_by_sql("SELECT * FROM recipes WHERE title LIKE '%#{params[:search]}%'")
     @users = User.find_by_sql("SELECT * FROM users WHERE firstname LIKE '%#{params[:search]}%'")
     render 'search'
  end

  def show
    if params[:id]
      @recipe = Recipe.find(params[:id])
    else
      @recipe = Recipe.find(params[:recipe_id])
    end
    if @recipe == nil
      flash[:error] = "No such recipe exists"
    end
    @favourite = Favourite.new
    @delete = Recipe.new
  end

  def favourite
    begin
      favourite_params =  params.require(:favourite).permit(:recipe_id)
      @favourite = Favourite.new(favourite_params)
      @favourite.user = @current_user
      if @favourite.save!
        redirect_to favourites_path()
      end
    rescue => e
      flash[:error] = e.message
      redirect_to favourites_path()
    end
  end

  def unfavourite
    unfavourite_params = params.require(:favourite).permit(:recipe_id)
    @unfavourite = Favourite.where("recipe_id = ? AND user_id = ?", unfavourite_params[:recipe_id], @current_user.id).take
    @unfavourite.destroy
    @unfavourite.save

    redirect_to favourites_path()
  end

  def favourites

  end

  def category
    @recipes = nil
  end

  def category_result
    category_params = params.require(:category).permit(:id)
    @recipes = Recipe.where("category_id =?", category_params[:id])

    render 'category'
  end

end

webFrameWorkProject/app/helpers/recipes_helper.rb
module RecipesHelper
end

webFrameWorkProject/app/views/recipes/category.html.erb
<div class="top_box">	
	<h1>Browse by category </h1>
</div>
<div class="main_box">
		<%= form_for Category.new, url: {controller: 'recipes', action: 'category_result'},  method: "get" do |t|%>
			<%= t.select :id, Category.all.collect{|p| [p.category, p.id]} %>
			<%= t.submit('Browse by category!')%>
		<% end %>


		<% if @recipes != nil %>
		<br/>
			<% @recipes.each do |d|%>
				<div class="list_recipe">
					<%= image_tag d.avatar.url(:thumb)%>
					<%= link_to d.title, show_path(:id => d.id) %>
					<div class="by">
						By: 
						<%= link_to d.feed.user.firstname, user_path(:id => d.feed.user.id) %>
					</div>
				</div><br/>
			<% end %>
			<% if @recipes == nil %>
				<p>No recipes added in choosen category :( </p>
			<% end %>
		<% end %>

</div>

webFrameWorkProject/app/views/recipes/create.html.erb
New recipe saved!

webFrameWorkProject/app/views/recipes/favourites.html.erb
<div class="top_box">	
	<h1>My favourite recipes</h1>
</div>
<div class="main_box">
	<% @current_user.favourites.each do |t| %>
		<div class="list_recipe">
			<%= image_tag t.recipe.avatar.url(:thumb)%>
			<%= link_to t.recipe.title, show_path(:recipe_id => t.recipe_id) %>
			<div class="by">
				By: 
				<%= link_to t.recipe.feed.user.firstname, user_path(:id => t.recipe.feed.user.id) %>
			</div>
		</div>
		
		<%= form_for Favourite.new, url: {controller: 'recipes', action: 'unfavourite'}, method: "get" do |d| %>
			<%= d.hidden_field(:recipe_id, :value => t.recipe.id) %>
			<%= d.submit('Unfavourite') %>
		<% end %>
		<br/>
	
	<% end %>
</div>

webFrameWorkProject/app/views/recipes/new.html.erb
<div class="top_box">
	<h1> Add new recipe</h1>
</div>
<div class="main_box">
	<%= form_for @recipe, url: {controller: 'recipes', action: 'create'}, :html => { :multipart => true } do |t| %>
		
		Recipe picture:<br/><br/>
		<%= t.file_field :avatar %><br/><br/>

		<%= t.label(:title, 'Title:') %><br/>
		<%= t.text_field(:title) %><br/>
		
		<%= t.label(:ingredients, 'Ingredients:')%><br/>
		<%= t.text_area(:ingredients)%><br/>
		
		<%= t.label(:instructions, 'Instructions:')%><br/>
		<%= t.text_area(:instructions)%><br/><br/>

		Choose a category:
		<%= t.select :category_id, Category.all.collect{|p| [p.category, p.id]} %><br/><br/>

		<%= t.submit('Save recipe!') %>
	
	<% end %>
</div>

webFrameWorkProject/app/views/recipes/results.html.erb
<% @recipe.each do |t| %>
	<%= t.title %><br/>
	<%= t.ingredients %><br/>
	<%= t.instructions %><br/>
<% end %>

webFrameWorkProject/app/views/recipes/search.html.erb
<div class="top_box">
	<h1>Search for recipes:</h1>
	<%= form_tag(results_path) do |t|%>
	  <%= text_field_tag(:search) %>
	  <%= submit_tag("Search") %> 
	<% end %>
</div>

<div class="main_box">
	<% if @current_user %>
		<h4><%= link_to "+ add a new recipe", newrecipe_path %></h4>
	<% else %>
		<%= link_to "Log in to add recipes", log_in_path() %>
	<% end %>
	
	<h3><%= @page_header %></h3>
	<% if @users != nil %>
			<div class="search_result_header">
				Recipes: 
			</div></br>
	<% end %>
	<% @recipes.each do |t| %>
		<div class="list_recipe">
			<%= image_tag t.avatar.url(:thumb)%>
			<%= link_to t.title, show_path(:id => t.id) %>
			<div class="by">
				By: 
				<%= link_to t.feed.user.firstname, user_path(:id => t.feed.user.id) %>
			</div>	
		</div><br/>
	<% end %>

	<% if @users != nil %>
		<div class="search_result_header">
			Users: 
		</div><br/>
		<% @users.each do |d| %>
			<div class="list_recipe">
				<%= image_tag d.avatar.url(:thumb) %>
				<%= link_to d.firstname, user_path(:id => d.id) %>
			</div><br/>
		<% end %>
	<% end %>
</div>

webFrameWorkProject/app/views/recipes/show.html.erb
<div class="top_box">	
	<h3><%= @recipe.title %><br/></h3>
</div>
<div class="main_box">
	<div class="show_recipe">
		<div class="by">
			by: <%= link_to @recipe.feed.user.firstname, user_path(:id => @recipe.feed.user.id) %><br/>
		</div><br/>
		<%= image_tag @recipe.avatar.url(:small) %><br/><br/>
		<h5>Ingredients: </h5><br/><br/>
		<%= @recipe.ingredients %><br/><br/>
		<h5>Instructions: </h5><br/><br/>
		<%= @recipe.instructions %><br/>
	</div><br/><br/>
		
	<% if @current_user%>
		<%= form_for @favourite, url: {controller: 'recipes', action: 'favourite'}, method: "get" do |t| %>
			<%= t.hidden_field(:recipe_id, :value => @recipe.id) %>
			<%= t.submit('Favourite') %>
		<% end %><br/>
		<% if @recipe.feed.user == @current_user %>
			<%= form_for @delete, url: {controller: 'recipes', action: 'delete'}, method: "get" do |d|%>
				<%= d.hidden_field(:recipe_id, :value => @recipe.id)%>
				<%= d.submit('Delete this recipe :(')%>
			<% end %>
		<% end %>
	<% else %>
			<%= link_to "Log in to favourite recipes!", log_in_path() %>
	<% end %>
</div>