webFrameWorkProject/config/routes.rb
WebFrameWorkProject::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  root 'recipes#search'

  get 'sign_up' => 'users#new'
  post 'registered' => 'users#create'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"

  get 'user' => 'users#show'
  
  get 'newrecipe' => 'recipes#new'
  get 'created' => 'recipes#create'
  post 'created' => 'recipes#create'

  get 'search' => 'recipes#search'
  post 'results' => 'recipes#results'

  get 'show' => 'recipes#show', :as => 'show'

  get 'favourite' => 'recipes#favourite', :as => 'favourite'
  get 'unfavourite' => 'recipes#unfavourite', :as => 'unfavourite'
  get 'favourites' => 'recipes#favourites', :as => 'favourites'

  get 'delete' => 'recipes#delete', :as => 'delete'

  get 'follow' => 'users#follow', :as => 'follow'
  get 'unfollow' => 'users#unfollow', :as => 'unfollow'
  get 'following' => 'users#following', :as => 'following'

  get 'category' => 'recipes#category', :as => 'category'
  get 'category_result' => 'recipes#category_result', :as => 'category_result'

end

webFrameWorkProject/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= yield(:title) %> </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
   <%= stylesheet_link_tag "custom", media: "all" %>
</head>
<body>
	<nav>
		<ul>
			<%if @current_user%>
				<li><a><%= link_to "Recipes", search_path %></a></li>
				<li><a><%= link_to "Categories", category_path %></a></li>
				<li><a><%= link_to "Favourites", favourites_path %></a></li>
				<li><a><%= link_to "Following", following_path %></a></li>
				<li><a><%= link_to "Profile", user_path(:id => @current_user.id) %></a></li>
				<li><a><%= link_to "Log out", log_out_path %></a></li>
			<% else %>
				<li><a><%= link_to "Recipes", search_path %></a></li>
				<li><a><%= link_to "Sign up", sign_up_path %></a></liS>
				<li><a><%= link_to "Log in", log_in_path %></a></li>
			<% end %>
		</ul>
	</nav>

	<section>
		<%= yield %>

	</section>
	
	<footer>
		<p>myRecipe</P>
	</footer>

</body>
</html>